### ISSUE TITLE
Null border in CircularClipRoute

### ISSUE THREAD

**Issue by PuntitOwO** [blaugold/circular_clip_route#1]
In `CircularClipTransition`, `border` is a `BoxBorder?` and docs say you can set it to null to disable it: 

> To disable the border, set [border] to `null`.

But in `CircularClipRoute`, `border` is a `Boxborder`, so you can't set it to null, so you can't disable border.

Please make `CircularClipRoute.border` nullable.

**Comment by blaugold** [comment]
Thanks for reporting this. I published a fix.
